### ISSUE TITLE
Error with this new version you commited few hours ago:

### ISSUE THREAD

**Issue by jimiero** [ITPrism/EmailTemplates#1]
Fatal error: Class 'Emailtemplates\Version' not found in administrator/components/com_emailtemplates/views/dashboard/view.html.php on line 40

**Comment by jimiero** [comment]
@ITPrism can you look on that ?

**Comment by ITPrism** [comment]
I changed the name space of email templates library to Emailtemplates. I am going to upload the new version in next few hours.
